### ISSUE TITLE
Accessing pinocchio model to obtain frameId

### ISSUE THREAD

**Issue by vcparedesc** [duburcqa/jiminy#392]
Hello!

I am using the pip method to build my project. Building the same project using jiminy from source would work, but now whenever I try to access the pinocchio model I get a segmentation fault. I am attaching a slightly modified version of the example pip_extension/double_pendulum.cc

Whenever I uncomment line 38:
``
  //auto Frame_id = robot->pncModel_.getFrameId("PendulumArm");
``

I get the segmentation fault. Am I using an outdated way to get the FrameId? 

Thanks!

[pip_extension.zip](https://github.com/duburcqa/jiminy/files/6940656/pip_extension.zip)

**Comment by vcparedesc** [comment]
I am attaching the bt
![BT1](https://user-images.githubusercontent.com/1549925/128397969-5dea23a6-ae52-4993-9284-560d43f5a1e1.png)
![BT2](https://user-images.githubusercontent.com/1549925/128397972-97cdf4ea-5bf9-4075-a6f3-924d9f0402fd.png)

**Comment by duburcqa** [comment]
Hum... I will have a look asap, but so far it looks like a mismatch between the version of Pinocchio used for compiling (header files) and the one imported at runtime using dynamic linking (shared library). Use `ldd` on the executable to know which library is used at runtime. Because it should work.

**Comment by vcparedesc** [comment]
This is the output from the cmake command:

```
-- Found jiminy ('1.6.28'): /home/victor/.local/lib/python3.8/site-packages/jiminy_py/core/include (/home/victor/.local/lib/python3.8/site-packages/jiminy_py/core/lib/libjiminy.so.1.6)
-- pinocchio FOUND. pinocchio at /opt/openrobots/lib/libpinocchio.so
-- boost_filesystem FOUND. boost_filesystem at /usr/lib/x86_64-linux-gnu/libboost_filesystem.so
-- boost_serialization FOUND. boost_serialization at /usr/lib/x86_64-linux-gnu/libboost_serialization.so
-- boost_system FOUND. boost_system at /usr/lib/x86_64-linux-gnu/libboost_system.so
-- Found Boost: /usr/include (found version "1.71.0") found components: filesystem serialization system 
-- hpp-fcl FOUND. hpp-fcl at /opt/openrobots/lib/libhpp-fcl.so
-- Found Boost: /usr/include (found version "1.71.0") found components: chrono serialization 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/victor/pip_extension/build
```
pinocchio.so is linking to the version 2.6.3. 
```
lrwxrwxrwx 1 500 355 21 Aug  3 07:05 libpinocchio.so -> libpinocchio.so.2.6.3
```

And ldd:
```
linux-vdso.so.1 (0x00007ffdb05e8000)
	libjiminy.so.1.6 => /home/victor/.local/lib/python3.8/site-packages/jiminy_py/core/lib/libjiminy.so.1.6 (0x00007f376ddb0000)
	libosqp.so => /home/victor/catkin_ws/devel/lib/libosqp.so (0x00007f376dd92000)
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f376db66000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f376da17000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f376d9fc000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f376d808000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f376f5cf000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f376d802000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f376d7f7000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f376d7d4000)

```

Is the pinocchio installed from [here](https://stack-of-tasks.github.io/pinocchio/download.html) the right version to use?

**Comment by duburcqa** [comment]
I'm going to have a look today ! Hope it is not too late x)

**Comment by duburcqa** [comment]
Ok it is running on my computer. So I think it is because there is a mismatch between the jiminy release you are using and the installed version of pinocchio. I should probably enforce the same version in cmake to avoid this kind of misleading issues.

**Comment by duburcqa** [comment]
Feel free to reopen if it is not fixed.
