### ISSUE TITLE
[misc] Bad docstring formatting for Boost::Python bindings.

### ISSUE THREAD

**Issue by Arpafaucon** [duburcqa/jiminy#565]
![image](https://user-images.githubusercontent.com/19834684/186889623-494d601a-4fbf-4b39-a334-cff776f49e3b.png)

I suppose the text documents an overload to the function, without being sure.

Also, is the `[ ]` nesting to indicate optionality correct ? This one indicates that `load_visual_meshes` being present is acceptable only if `has_freeflyer`  is present too

**Comment by duburcqa** [comment]
I'm afraid I cannot do much about it. This documentation is automatically generated by sphinx from boost python bindings. I don't know why there is this strange recursion of optional parameters, and the convention is strange overall.

**Comment by duburcqa** [comment]
[Here](https://github.com/boostorg/python/blob/f5d14ef15e98838b3cf18692d46c481287ed50d0/src/object/function_doc_signature.cpp#L179) is the culprit !

**Comment by duburcqa** [comment]
Stubs files are now provided. Just waiting for Sphinx to support `pyi` files to generate doc. This issue is documented [here](https://github.com/sphinx-doc/sphinx/issues/7630#issuecomment-1464457759).
