### ISSUE TITLE
[jiminy/log] More effective way to restore model.

### ISSUE THREAD

**Issue by duburcqa** [duburcqa/jiminy#594]
It would be more efficient and clearer to loop over all the attributes of `__dict__` or `vars` instead of leveraging the serialization capability of pinocchio itself [here](
https://github.com/duburcqa/jiminy/blob/809ecf0a2e9d2cf7984cc7937ab4f269bb289327/python/jiminy_py/src/jiminy_py/log.py#LL204C9-L204C48):
```python
for name in dir(pinocchio_model):
    setattr(robot.pinocchio_model, name, getattr(pinocchio_model, name))
for name, value in vars(pinocchio_data).items():
    setattr(robot.pinocchio_data, name, getattr(pinocchio_data, name))
```

or may even more simple:
```python
robot.pinocchio_model.__dict__.update(pinocchio_model.__dict__)
robot.pinocchio_data.__dict__.update(pinocchio_data.__dict__)
```

PS: check that assignment does not change memory addresses

**Comment by jcarpent** [comment]
I don’t think this solution will be faster than internal Pinocchio serialization

**Comment by duburcqa** [comment]
In the end I'm going for:
```
robot.pinocchio_model.__setstate__(pinocchio_model.__getstate__())
pinocchio_data = pin.Data(pinocchio_model)
robot.pinocchio_data.__setstate__(pinocchio_data.__getstate__())
```

**Comment by jcarpent** [comment]
So using Pinocchio serialization

**Comment by duburcqa** [comment]
yes, It makes more sense like this, because relying on `__dict__` turns out to be hazardous because some attributes may be read-only.
