### ISSUE TITLE
[gym] Ensure values passed to episode.hist_data are of native types

### ISSUE THREAD

**Issue by mwulfman** [duburcqa/jiminy#665]
In python/gym_jiminy/rllib/gym_jiminy/rllib/callbacks.py, line 45:
`
                episode.hist_data.setdefault(key, []).append(value)
`

if `value` is not of native type (i.e. for instance if it is numpy.float or numpy.int), it can create significant bottlenecks resulting in an important slow-down in training.

This is likely caused by Tensorboard.

**Comment by duburcqa** [comment]
no longer relevant.
