### ISSUE TITLE
[gym_jiminy] BaseJiminyEnv doesn't support single-robot simulators with a robot name different from ""

### ISSUE THREAD

**Issue by mwulfman** [duburcqa/jiminy#772]
The following line not only checks that there is only one robot in the simulator, but it also forces the name of the single robot to be "".

```python
        if tuple(robot.name for robot in simulator.robots) != ("",):
            raise ValueError(
                "`BaseJiminyEnv` only supports single-robot simulators.")
```

**Comment by duburcqa** [comment]
This limitation is necessary at the time being, otherwise `plot` would fail. This will be fixed by https://github.com/duburcqa/jiminy/pull/770.
